# Generated by Django 2.2.3 on 2021-04-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_customer', models.CharField(max_length=50)),
                ('to_customer', models.CharField(max_length=50)),
                ('balance_transferred', models.FloatField()),
            ],
        ),
    ]
